//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/rk/or/android/ModelSelection.java
//
//  Created by remi on 10/05/13.
//

#import "AbsListView.h"
#import "Activity.h"
#import "AdapterView.h"
#import "Bundle.h"
#import "GridView.h"
#import "IOSClass.h"
#import "IOSObjectArray.h"
#import "ImageView.h"
#import "Intent.h"
#import "ModelSelection.h"
#import "ModelView.h"
#import "R.h"
#import "View.h"
#import "View3D.h"
#import "ViewGroup.h"
#import "java/lang/Integer.h"

@implementation AndroidModelSelection

@synthesize mThumbIds = mThumbIds_;
@synthesize mModels = mModels_;

- (void)onCreateWithAndroidOsBundle:(AndroidOsBundle *)savedInstanceState {
  [super onCreateWithAndroidOsBundle:savedInstanceState];
  [self setContentViewWithInt:AndroidR_layout_layout_model_selection];
  AndroidWidgetGridView *grid = (AndroidWidgetGridView *) [self findViewByIdWithInt:AndroidR_id_grid];
  [((AndroidWidgetGridView *) grid) setBackgroundResourceWithInt:AndroidR_drawable_background256x256];
  [((AndroidWidgetGridView *) grid) setAdapterWithAndroidWidgetListAdapter:[[AndroidModelSelection_AppsAdapter alloc] initWithAndroidModelSelection:self]];
  [((AndroidWidgetGridView *) grid) setOnItemClickListenerWithAndroidWidgetAdapterView_OnItemClickListener:self];
}

- (void)onItemClickWithAndroidWidgetAdapterView:(AndroidWidgetAdapterView *)parent
                            withAndroidViewView:(AndroidViewView *)view
                                        withInt:(int)position
                                    withLongInt:(long long int)id_ {
  if ([AndroidView3D front] == 0) {
    (*[AndroidView3D texturesONRef]) = YES;
    (*[AndroidView3D frontRef]) = AndroidR_drawable_gally400x572;
    (*[AndroidView3D backRef]) = AndroidR_drawable_sunako400x572;
    (*[AndroidView3D backgroundRef]) = AndroidR_drawable_background256x256;
  }
  if (id_ == (int) [((IOSObjectArray *) self.mThumbIds) count] - 2) {
    (*[AndroidView3D texturesONRef]) = NO;
    return;
  }
  if (id_ == (int) [((IOSObjectArray *) self.mThumbIds) count] - 1) {
    (*[AndroidView3D texturesONRef]) = YES;
    (*[AndroidView3D frontRef]) = AndroidR_drawable_gally400x572;
    (*[AndroidView3D backRef]) = AndroidR_drawable_sunako400x572;
    (*[AndroidView3D backgroundRef]) = AndroidR_drawable_background256x256;
    return;
  }
  [self startActivityWithAndroidContentIntent:[((AndroidContentIntent *) [[AndroidContentIntent alloc] initWithAndroidContentContext:self withIOSClass:[IOSClass classWithClass:[AndroidModelView class]]]) putExtraWithNSString:@"model" withNSString:[((IOSObjectArray * self.mModels) objectAtIndex:position])]];
  return;
}

- (id)init {
  if ((self = [super init])) {
    self.mThumbIds = [IOSObjectArray arrayWithObjects:(id[]){ [JavaLangInteger valueOfWithInt:AndroidR_drawable_cocotte72x72], [JavaLangInteger valueOfWithInt:AndroidR_drawable_duck72x72], [JavaLangInteger valueOfWithInt:AndroidR_drawable_boat72x72], [JavaLangInteger valueOfWithInt:AndroidR_drawable_austria72x72], [JavaLangInteger valueOfWithInt:AndroidR_drawable_blueyellow72x72], [JavaLangInteger valueOfWithInt:AndroidR_drawable_gally72x72] } count:6 type:[IOSClass classWithClass:[JavaLangInteger class]]];
    self.mModels = [IOSObjectArray arrayWithObjects:(id[]){ @"cocotte.txt", @"duck.txt", @"boat.txt", @"austria.txt", @"cocotte.txt", @"cocotte.txt" } count:6 type:[IOSClass classWithClass:[NSString class]]];
  }
  return self;
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  AndroidModelSelection *typedCopy = (AndroidModelSelection *) copy;
  typedCopy.mThumbIds = mThumbIds_;
  typedCopy.mModels = mModels_;
}

@end
@implementation AndroidModelSelection_AppsAdapter

@synthesize this$0 = this$0_;

- (AndroidViewView *)getViewWithInt:(int)position
                withAndroidViewView:(AndroidViewView *)convertView
           withAndroidViewViewGroup:(AndroidViewViewGroup *)parent {
  AndroidWidgetImageView *i = [[AndroidWidgetImageView alloc] initWithAndroidContentContext:self.this$0];
  [((AndroidWidgetImageView *) i) setImageResourceWithInt:[((JavaLangInteger *) [((IOSObjectArray *) self.this$0.mThumbIds) objectAtIndex:position]) intValue]];
  [((AndroidWidgetImageView *) i) setScaleTypeWithAndroidWidgetImageView_ScaleTypeEnum:[AndroidWidgetImageView_ScaleTypeEnum FIT_CENTER]];
  [((AndroidWidgetImageView *) i) setLayoutParamsWithAndroidViewViewGroup_LayoutParams:[[AndroidWidgetAbsListView_LayoutParams alloc] initWithInt:170 withInt:170]];
  return i;
}

- (int)getCount {
  return (int) [((IOSObjectArray *) self.this$0.mThumbIds) count];
}

- (id)getItemWithInt:(int)position {
  return [JavaLangInteger valueOfWithInt:position];
}

- (long long int)getItemIdWithInt:(int)position {
  return position;
}

- (id)initWithAndroidModelSelection:(AndroidModelSelection *)outer$ {
  if ((self = [super init])) {
    self.this$0 = outer$;
  }
  return self;
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  AndroidModelSelection_AppsAdapter *typedCopy = (AndroidModelSelection_AppsAdapter *) copy;
  typedCopy.this$0 = this$0_;
}

@end
